Default: &defaults
  user: yist
  password: yist
  host: localhost
  database: yist-in-git
  connections: 10

Development:
  <<: *defaults

Testing:
  database: yist_test
  <<: *defaults

Staging:
  database: yist_staging
  connections: 100
  <<: *defaults

Production:
  database: yist_production
  connections: 100
  host: localhost
  <<: *defaults
